catch (Exception exc) {
    Exception exc2 = exc;
}